# coding=utf8
import sys, os

NO = 0
YES = 1

INTERNAL_INCIDENT_SYNCHER_INTERVAL = 'INTERVAL 1 DAY'

MYSQLDB_MONITORING_ASSISTANT_CONFIG = 'MYSQLDB_MONITORING_ASSISTANT'
MONGODB_MONITORING_ASSISTANT_CONFIG = 'MONGODB_MONITORING_ASSISTANT'
MONGODB_MASTER_CONFIG               = 'MONGODB_MASTER'
ITSM_API_CONFIG                     = 'ITSM_API'
G8_API_CONFIG                       = 'G8_API'
CS_API_CONFIG                       = 'CS_API'
PROMOTION_API_CONFIG                = 'PROMOTION_API'
MAIL_SERVER_CONFIG					= 'MAIL_SERVER'
G8_MAIL_SENDER_CONFIG				= 'G8_MAIL_SENDER'

CONFIG_FILENAME = 'Config.ini'

TBL_ACTIVE_COLLECTION_INFO 		= 'zabbix_changes'
TBL_INCIDENT_WAITING_OPEN  		= 'incident_create_history'
TBL_INCIDENT_WAITING_UPDATE  	= 'incident_update_history'
TBL_INCIDENT_FOLLOW        		= 'incident_follow'
TBL_ALERT_G8               		= 'g8_alerts'
TBL_ALERT_CS               		= 'cs_alerts'
TBL_ALERT_PROMOTION             = 'promotion_alerts'
TBL_ALERT_ZABBIX                = 'alerts'
TBL_SEND_MAIL             		= 'send_mail'
TBL_CENTRAL_ALERT         		= 'monitoring_assistant_alerts'
TBL_ALERT_ACK                   = 'alerts_ack'
TBL_EXTERNAL_ATTACHMENTS		= 'external_attachments'
TBL_INCIDENT_TRACKING_CHANGES   = 'incident_tracking_changes'

INCIDENT_SRC_FROM_G8        = 'g8'
INCIDENT_SRC_FROM_CS        = 'cs'
INCIDENT_SRC_FROM_PROMOTION = 'promotion'
INCIDENT_SRC_FROM_ZABBIX    = 'zabbix'
INCIDENT_SRC_FROM_SO6		= 'so6'

SRC_FROM_TABLE_MAP = {INCIDENT_SRC_FROM_G8:TBL_ALERT_G8, INCIDENT_SRC_FROM_CS:TBL_ALERT_CS, INCIDENT_SRC_FROM_PROMOTION:TBL_ALERT_PROMOTION, INCIDENT_SRC_FROM_ZABBIX:TBL_ALERT_ZABBIX}

VNG_LOGO_CONTENT_ID = 'vnglogo'
VNG_LOGO_IMAGE = 'vng_logo.jpg'

G8_MAIL_INFORM_SUBJECT = '[SDK] Thông báo về việc ghi nhận Incident'

INCIDENT_STATUS_RESOLVE = 'Resolved'
INCIDENT_STATUS_REOPEN = 'Reopen'

LIST_STATUS_INCIDENT_WAITING_OPEN = "'1'"
LIST_STATUS_INCIDENT_CLOSED       = "'closed'"

LIST_STATUS_INCIDENT_WAITING_UPDATE = "'0', '2'"
STATUS_INCIDENT_UPDATE_SUCCESS = 1

#URL_ITSM_CREATE_INCIDENT = 'http://10.30.57.113:8080/IncidenManagement/createIncident?data='
#URL_ITSM_CREATE_INCIDENT = 'http://localhost:10000/IncidenManagement/createIncident?data='
#URL_ITSM_UPDATE_INCIDENT = 'http://10.30.57.113:8080/IncidenManagement/updateIncident?data='
#URL_ITSM_CREATE_INCIDENT = 'http://10.30.15.14:8080/IncidenManagement/createIncident?data='
#URL_ITSM_UPDATE_INCIDENT = 'http://10.30.15.14:8080/IncidenManagement/updateIncident?data='

ITSM_STATUS_INITIALIZE = 0
ITSM_STATUS_OK         = 1
ITSM_STATUS_FAIL       = 2

ITSM_INC_UPDATE = 'update'
ITSM_INC_CREATE = 'create'
ITSM_INC_CREATE_PATTERN_SUCCESS = 'Create SUCCESS'
ITSM_INC_CREATE_PATTERN_FAIL    = 'Create FAILURE'
ITSM_INC_CREATE_PATTERN_ITSM_ID = '/Incident ID.+(IM\d+)/i'
ITSM_INC_CREATE_PATTERN_RETURN_CODE = '/Return Code.+\d+/i'
ITSM_INC_CREATE_PATTERN_RETURN_MSG  = '/Message.+\n.+\n/i'

ITSM_INC_UPDATE_PATTERN_SUCCESS = 'Update SUCCESS'
ITSM_INC_UPDATE_PATTERN_FAIL    = 'Update FAILURE'
ITSM_INC_UPDATE_PATTERN_ITSM_ID = '/Incident ID.+(IM\d+)/i'
ITSM_INC_UPDATE_PATTERN_RETURN_CODE = '/Return Code.+\d+/i'
ITSM_INC_UPDATE_PATTERN_RETURN_MSG  = '/Message.+\n.+\n/i'

ITSM_INC_RESOLVE_PATTERN_SUCCESS = 'Resolve SUCCESS'
ITSM_INC_RESOLVE_PATTERN_FAIL    = 'Resolve FAILURE'
ITSM_INC_RESOLVE_PATTERN_ITSM_ID = '/Incident ID.+(IM\d+)/i'
ITSM_INC_RESOLVE_PATTERN_RETURN_CODE = '/Return Code.+\d+/i'
ITSM_INC_RESOLVE_PATTERN_RETURN_MSG  = '/Message.+\n.+\n/i'

ITSM_INC_REOPEN_PATTERN_SUCCESS = 'Resolve SUCCESS'
ITSM_INC_REOPEN_PATTERN_FAIL    = 'Resolve FAILURE'
ITSM_INC_REOPEN_PATTERN_ITSM_ID = '/Incident ID.+(IM\d+)/i'
ITSM_INC_REOPEN_PATTERN_RETURN_CODE = '/Return Code.+\d+/i'
ITSM_INC_REOPEN_PATTERN_RETURN_MSG  = '/Message.+\n.+\n/i'

ITSM_INC_ID_KEY_PATTERN = 'Incident ID'
SDK_INC_SUCCESS_PATTERN = 'success'

ITSM_RETRY_TIMES = 100

PYTHON_DATE_FORMAT_MYSQL = '%Y-%m-%d %H:%M:%S'
PYTHON_DATE_FORMAT_G8    = '%Y-%m-%d %H:%M:%S'
MYSQL_DATE_FORMAT_ITSM   = '%m/%d/%y %H:%i:%s'
MYSQL_DATE_FORMAT_MYSQL  = '%y-%m-%d %H:%i:%s'


MYSQL_FUNCTION_GET_CURRENT_SHIFT_ID     = 'f_get_current_shift()'
MYSQL_FUNCTION_GET_CURRENT_SHIFT_LEADER = 'f_get_current_shift_leader()'
MYSQL_VALUE_TYPE_EXPRESSION             = 'expression'
MYSQL_VALUE_TYPE_FUNCTION               = 'function'

INCIDENT_WAITING_STATUS_WAITING = 1
INCIDENT_WAITING_STATUS_OPENED  = 2
INCIDENT_WAITING_STATUS_FAIL    = 3

LOG_SEPERATOR = "\n#--------------------------------------------------------------------------------#"

RAW_ALERT_STATUS_INIT          = 0
RAW_ALERT_STATUS_CENTRALIZED   = 1
RAW_ALERT_STATUS_ITSM_OPENNED  = 2
RAW_ALERT_STATUS_ITSM_CLOSED   = 3
RAW_ALERT_STATUS_ITSM_REOPEN   = 4
RAW_ALERT_STATUS_ITSM_REJECTED = 5
RAW_ALERT_STATUS_ITSM_RESOLVED = 6

ITSM_STATUS_OPEN = 'open'
SEND_MAIL_STATUS_WAITING = 0

API_G8_FUNCTION_UPDATE_INCIDENT_STATUS = 'update_status_incident'
API_G8_MODEL  = 'vng.cstool.sdk.interface'
API_G8_RESPONSE_ERROR_CODE_KEY = '0'

SLEEP_DEFAULT               = 2
SLEEP_NOTIFY_ITSM_STATUS    = 1
SLEEP_OPEN_WAITING_INCIDENT = SLEEP_DEFAULT
SLEEP_PROMOTION_ALERT       = 5
SLEEP_SEND_MAIL				= 5

CENTRAL_ALERT_STATUS_OFF  = 0
CENTRAL_ALERT_STATUS_SHOW = 1
CENTRAL_ALERT_STATUS_REPLACED = 2