/* rcx.h
   Generated by wsdl2h 2.8.16 from http://api.sdk.td.vn/SDKSupportService04/SDKSuportSerivces.svc?wsdl and typemap.dat
   2013-11-23 03:31:50 GMT

   DO NOT INCLUDE THIS FILE DIRECTLY INTO YOUR PROJECT BUILDS
   USE THE soapcpp2-GENERATED SOURCE CODE FILES FOR YOUR PROJECT BUILDS

   gSOAP XML Web services tools.
   Copyright (C) 2000-2013 Robert van Engelen, Genivia Inc. All Rights Reserved.
   Part of this software is released under one of the following licenses:
   GPL or Genivia's license for commercial use.
*/

/** @page page_notes Usage Notes

NOTE:

 - Run soapcpp2 on rcx.h to generate the SOAP/XML processing logic.
   Use soapcpp2 -I to specify paths for #import
   To build with STL, 'stlvector.h' is imported from 'import' dir in package.
   Use soapcpp2 -j to generate improved proxy and server classes.
 - Use wsdl2h -c and -s to generate pure C code or C++ code without STL.
 - Use 'typemap.dat' to control namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Use Doxygen (www.doxygen.org) on this file to generate documentation.
 - Use wsdl2h -R to generate REST operations.
 - Use wsdl2h -nname to use name as the base namespace prefix instead of 'ns'.
 - Use wsdl2h -Nname for service prefix and produce multiple service bindings
 - Use wsdl2h -d to enable DOM support for xsd:anyType.
 - Use wsdl2h -g to auto-generate readers and writers for root elements.
 - Use wsdl2h -b to auto-generate bi-directional operations (duplex ops).
 - Struct/class members serialized as XML attributes are annotated with a '@'.
 - Struct/class members that have a special role are annotated with a '$'.

WARNING:

   DO NOT INCLUDE THIS ANNOTATED FILE DIRECTLY IN YOUR PROJECT SOURCE CODE.
   USE THE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT'S SOURCE CODE:
   THE soapStub.h FILE CONTAINS THIS CONTENT WITHOUT ANNOTATIONS.

LICENSE:

@verbatim
--------------------------------------------------------------------------------
gSOAP XML Web services tools
Copyright (C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.

This software is released under one of the following licenses:
GPL or Genivia's license for commercial use.
--------------------------------------------------------------------------------
GPL license.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 59 Temple
Place, Suite 330, Boston, MA 02111-1307 USA

Author contact information:
engelen@genivia.com / engelen@acm.org

This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial-use license is available from Genivia, Inc., contact@genivia.com
--------------------------------------------------------------------------------
@endverbatim

*/


//gsoapopt cw

/******************************************************************************\
 *                                                                            *
 * Definitions                                                                *
 *   http://tempuri.org/                                                      *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

ns1 = "http://tempuri.org/"
ns2 = "http://tempuri.org/Imports"
ns3 = "http://schemas.microsoft.com/2003/10/Serialization/"

*/

#define SOAP_NAMESPACE_OF_ns2	"http://tempuri.org/Imports"
//gsoap ns2   schema namespace:	http://tempuri.org/Imports
//gsoap ns2   schema form:	unqualified

#define SOAP_NAMESPACE_OF_ns1	"http://tempuri.org/"
//gsoap ns1   schema namespace:	http://tempuri.org/
//gsoap ns1   schema elementForm:	qualified
//gsoap ns1   schema attributeForm:	unqualified

#define SOAP_NAMESPACE_OF_ns3	"http://schemas.microsoft.com/2003/10/Serialization/"
//gsoap ns3   schema namespace:	http://schemas.microsoft.com/2003/10/Serialization/
//gsoap ns3   schema form:	qualified

/******************************************************************************\
 *                                                                            *
 * Built-in Schema Types and Top-Level Elements and Attributes                *
 *                                                                            *
\******************************************************************************/


/// Built-in type "xs:base64Binary".
struct xsd__base64Binary
{	unsigned char *__ptr;
	int __size;
	char *id, *type, *options; // NOTE: non-NULL for DIMEM/MIME/MTOM XOP attachments only
};

/// Built-in type "xs:boolean".
enum xsd__boolean { xsd__boolean__false_, xsd__boolean__true_ };

/// Built-in type "xs:byte".
typedef char xsd__byte;

/// Built-in type "xs:unsignedByte".
typedef unsigned char xsd__unsignedByte;

/// Primitive built-in type "xs:ID"
typedef char* xsd__ID;

/// Primitive built-in type "xs:IDREF"
typedef char* xsd__IDREF;

/// Primitive built-in type "xs:anyURI"
typedef char* xsd__anyURI;

/// Primitive built-in type "xs:decimal"
typedef char* xsd__decimal;

/// Primitive built-in type "xs:duration"
typedef char* xsd__duration;


/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   http://tempuri.org/Imports                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   http://tempuri.org/                                                      *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   http://schemas.microsoft.com/2003/10/Serialization/                      *
 *                                                                            *
\******************************************************************************/


/// "http://schemas.microsoft.com/2003/10/Serialization/":char is a simpleType restriction of xs:int.
typedef int ns3__char;

/// "http://schemas.microsoft.com/2003/10/Serialization/":duration is a simpleType restriction of xs:duration.
/// Content pattern is "\\-?P(\\d*D)?(T(\\d*H)?(\\d*M)?(\\d*(\\.\\d*)?S)?)?" (note: not automatically enforced)
/// Value range is [-P10675199DT2H48M5.4775808S..P10675199DT2H48M5.4775807S]
typedef xsd__duration ns3__duration "\\-?P(\\d*D)?(T(\\d*H)?(\\d*M)?(\\d*(\\.\\d*)?S)?)?";

/// "http://schemas.microsoft.com/2003/10/Serialization/":guid is a simpleType restriction of xs:string.
/// Content pattern is "[\\da-fA-F]{8}-[\\da-fA-F]{4}-[\\da-fA-F]{4}-[\\da-fA-F]{4}-[\\da-fA-F]{12}" (note: not automatically enforced)
typedef char* ns3__guid "[\\da-fA-F]{8}-[\\da-fA-F]{4}-[\\da-fA-F]{4}-[\\da-fA-F]{4}-[\\da-fA-F]{12}";

/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   http://tempuri.org/Imports                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   http://tempuri.org/                                                      *
 *                                                                            *
\******************************************************************************/



/// Top-level root element "http://tempuri.org/":GetListINC

/// "http://tempuri.org/":GetListINC is a complexType.
struct _ns1__GetListINC
{
/// Element sigkey of type xs:string.
    char*                                sigkey                         0;	///< Nillable pointer.
};


/// Top-level root element "http://tempuri.org/":GetListINCResponse

/// "http://tempuri.org/":GetListINCResponse is a complexType.
struct _ns1__GetListINCResponse
{
/// Element GetListINCResult of type xs:string.
    char*                                GetListINCResult               0;	///< Nillable pointer.
};


/// Top-level root element "http://tempuri.org/":UpdateStatusINC

/// "http://tempuri.org/":UpdateStatusINC is a complexType.
struct _ns1__UpdateStatusINC
{
/// Element INCCode of type xs:string.
    char*                                INCCode                        0;	///< Nillable pointer.
/// Element INCStatusID of type xs:short.
    short*                               INCStatusID                    0;	///< Optional element.
/// Element ITSMCode of type xs:string.
    char*                                ITSMCode                       0;	///< Nillable pointer.
/// Element CreatedBy of type xs:string.
    char*                                CreatedBy                      0;	///< Nillable pointer.
/// Element Comment of type xs:string.
    char*                                Comment                        0;	///< Nillable pointer.
/// Element ITSMCloseDate of type xs:string.
    char*                                ITSMCloseDate                  0;	///< Nillable pointer.
/// Element sigkey of type xs:string.
    char*                                sigkey                         0;	///< Nillable pointer.
};


/// Top-level root element "http://tempuri.org/":UpdateStatusINCResponse

/// "http://tempuri.org/":UpdateStatusINCResponse is a complexType.
struct _ns1__UpdateStatusINCResponse
{
/// Element UpdateStatusINCResult of type xs:string.
    char*                                UpdateStatusINCResult          0;	///< Nillable pointer.
};

/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   http://schemas.microsoft.com/2003/10/Serialization/                      *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   http://tempuri.org/Imports                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   http://tempuri.org/Imports                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   http://tempuri.org/                                                      *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   http://tempuri.org/                                                      *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   http://schemas.microsoft.com/2003/10/Serialization/                      *
 *                                                                            *
\******************************************************************************/


/// Top-level root element "http://schemas.microsoft.com/2003/10/Serialization/":anyType of type xs:anyType.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://schemas.microsoft.com/2003/10/Serialization/":anyURI of type xs:anyURI.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://schemas.microsoft.com/2003/10/Serialization/":base64Binary of type xs:base64Binary.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://schemas.microsoft.com/2003/10/Serialization/":boolean of type xs:boolean.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://schemas.microsoft.com/2003/10/Serialization/":byte of type xs:byte.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://schemas.microsoft.com/2003/10/Serialization/":dateTime of type xs:dateTime.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://schemas.microsoft.com/2003/10/Serialization/":decimal of type xs:decimal.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://schemas.microsoft.com/2003/10/Serialization/":double of type xs:double.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://schemas.microsoft.com/2003/10/Serialization/":float of type xs:float.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://schemas.microsoft.com/2003/10/Serialization/":int of type xs:int.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://schemas.microsoft.com/2003/10/Serialization/":long of type xs:long.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://schemas.microsoft.com/2003/10/Serialization/":QName of type xs:QName.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://schemas.microsoft.com/2003/10/Serialization/":short of type xs:short.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://schemas.microsoft.com/2003/10/Serialization/":string of type xs:string.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://schemas.microsoft.com/2003/10/Serialization/":unsignedByte of type xs:unsignedByte.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://schemas.microsoft.com/2003/10/Serialization/":unsignedInt of type xs:unsignedInt.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://schemas.microsoft.com/2003/10/Serialization/":unsignedLong of type xs:unsignedLong.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://schemas.microsoft.com/2003/10/Serialization/":unsignedShort of type xs:unsignedShort.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://schemas.microsoft.com/2003/10/Serialization/":char of type "http://schemas.microsoft.com/2003/10/Serialization/":char.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://schemas.microsoft.com/2003/10/Serialization/":duration of type "http://schemas.microsoft.com/2003/10/Serialization/":duration.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://schemas.microsoft.com/2003/10/Serialization/":guid of type "http://schemas.microsoft.com/2003/10/Serialization/":guid.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   http://schemas.microsoft.com/2003/10/Serialization/                      *
 *                                                                            *
\******************************************************************************/


/// Top-level attribute "http://schemas.microsoft.com/2003/10/Serialization/":FactoryType of simpleType xs:QName.
/// Note: use wsdl2h option -g to auto-generate a top-level attribute declaration and processing code.

/// Top-level attribute "http://schemas.microsoft.com/2003/10/Serialization/":Id of simpleType xs:ID.
/// Note: use wsdl2h option -g to auto-generate a top-level attribute declaration and processing code.

/// Top-level attribute "http://schemas.microsoft.com/2003/10/Serialization/":Ref of simpleType xs:IDREF.
/// Note: use wsdl2h option -g to auto-generate a top-level attribute declaration and processing code.

/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/

// This service supports SOAP 1.2 namespaces:
#import "soap12.h"

//gsoap ns1  service name:	BasicHttpBinding_USCOREISDKSuportSerivces 
//gsoap ns1  service type:	ISDKSuportSerivces 
//gsoap ns1  service port:	http://api.sdk.td.vn/SDKSupportService04/SDKSuportSerivces.svc 
//gsoap ns1  service namespace:	http://tempuri.org/ 
//gsoap ns1  service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage SDKSuportSerivces Definitions

@section SDKSuportSerivces_bindings Service Bindings

  - @ref BasicHttpBinding_USCOREISDKSuportSerivces

@section SDKSuportSerivces_more More Information

  - @ref page_notes "Usage Notes"

  - @ref page_XMLDataBinding "XML Data Binding"

  - @ref SOAP_ENV__Header "SOAP Header Content" (when applicable)

  - @ref SOAP_ENV__Detail "SOAP Fault Detail Content" (when applicable)


*/

/**

@page BasicHttpBinding_USCOREISDKSuportSerivces Binding "BasicHttpBinding_USCOREISDKSuportSerivces"

@section BasicHttpBinding_USCOREISDKSuportSerivces_operations Operations of Binding  "BasicHttpBinding_USCOREISDKSuportSerivces"

  - @ref __ns1__GetListINC

  - @ref __ns1__UpdateStatusINC

@section BasicHttpBinding_USCOREISDKSuportSerivces_ports Endpoints of Binding  "BasicHttpBinding_USCOREISDKSuportSerivces"

  - http://api.sdk.td.vn/SDKSupportService04/SDKSuportSerivces.svc

Note: use wsdl2h option -Nname to change the service binding prefix name


*/

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   BasicHttpBinding_USCOREISDKSuportSerivces                                *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__GetListINC                                                        *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__GetListINC" of service binding "BasicHttpBinding_USCOREISDKSuportSerivces"

/**

Operation details:

  - SOAP document/literal style messaging

  - Action: "http://tempuri.org/ISDKSuportSerivces/GetListINC"

  - Addressing input action: "http://tempuri.org/ISDKSuportSerivces/GetListINC"

  - Addressing output action: "http://tempuri.org/ISDKSuportSerivces/GetListINCResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__GetListINC(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    struct _ns1__GetListINC*            ns1__GetListINC,
    // output parameters:
    struct _ns1__GetListINCResponse*    ns1__GetListINCResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__GetListINC(
    struct soap *soap,
    // input parameters:
    struct _ns1__GetListINC*            ns1__GetListINC,
    // output parameters:
    struct _ns1__GetListINCResponse*    ns1__GetListINCResponse
  );
@endcode

*/

//gsoap ns1  service method-protocol:	GetListINC SOAP
//gsoap ns1  service method-style:	GetListINC document
//gsoap ns1  service method-encoding:	GetListINC literal
//gsoap ns1  service method-input-action:	GetListINC http://tempuri.org/ISDKSuportSerivces/GetListINC
//gsoap ns1  service method-output-action:	GetListINC http://tempuri.org/ISDKSuportSerivces/GetListINCResponse
int __ns1__GetListINC(
    struct _ns1__GetListINC*            ns1__GetListINC,	///< Input parameter
    struct _ns1__GetListINCResponse*    ns1__GetListINCResponse	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__UpdateStatusINC                                                   *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__UpdateStatusINC" of service binding "BasicHttpBinding_USCOREISDKSuportSerivces"

/**

Operation details:

  - SOAP document/literal style messaging

  - Action: "http://tempuri.org/ISDKSuportSerivces/UpdateStatusINC"

  - Addressing input action: "http://tempuri.org/ISDKSuportSerivces/UpdateStatusINC"

  - Addressing output action: "http://tempuri.org/ISDKSuportSerivces/UpdateStatusINCResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__UpdateStatusINC(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    struct _ns1__UpdateStatusINC*       ns1__UpdateStatusINC,
    // output parameters:
    struct _ns1__UpdateStatusINCResponse* ns1__UpdateStatusINCResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__UpdateStatusINC(
    struct soap *soap,
    // input parameters:
    struct _ns1__UpdateStatusINC*       ns1__UpdateStatusINC,
    // output parameters:
    struct _ns1__UpdateStatusINCResponse* ns1__UpdateStatusINCResponse
  );
@endcode

*/

//gsoap ns1  service method-protocol:	UpdateStatusINC SOAP
//gsoap ns1  service method-style:	UpdateStatusINC document
//gsoap ns1  service method-encoding:	UpdateStatusINC literal
//gsoap ns1  service method-input-action:	UpdateStatusINC http://tempuri.org/ISDKSuportSerivces/UpdateStatusINC
//gsoap ns1  service method-output-action:	UpdateStatusINC http://tempuri.org/ISDKSuportSerivces/UpdateStatusINCResponse
int __ns1__UpdateStatusINC(
    struct _ns1__UpdateStatusINC*       ns1__UpdateStatusINC,	///< Input parameter
    struct _ns1__UpdateStatusINCResponse* ns1__UpdateStatusINCResponse	///< Output parameter
);

/**

@page BasicHttpBinding_USCOREISDKSuportSerivces Binding "BasicHttpBinding_USCOREISDKSuportSerivces"

@section BasicHttpBinding_USCOREISDKSuportSerivces_policy_enablers Policy Enablers of Binding  "BasicHttpBinding_USCOREISDKSuportSerivces"

Based on policies, this service imports

  - WS-Policy reminders and enablers:
    - WS-Addressing 1.0 (2005/08, accepts 2004/08):
	@code
	#import "wsa5.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsaapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	// See the user guide gsoap/doc/wsa/html/index.html
	@endcode
    - WS-Addressing (2004/08):
	@code
	#import "wsa.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsaapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	// See the user guide gsoap/doc/wsa/html/index.html
	@endcode
    - WS-ReliableMessaging 1.0:
	@code
	#import "wsrm5.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsrmapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	soap_register_plugin(soap, soap_wsrm); // register the wsrm plugin in your code
	// See the user guide gsoap/doc/wsrm/html/index.html
	@endcode
    - WS-ReliableMessaging 1.1:
	@code
	#import "wsrm.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsrmapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	soap_register_plugin(soap, soap_wsrm); // register the wsrm plugin in your code
	// See the user guide gsoap/doc/wsrm/html/index.html
	@endcode
    - WS-Security (SOAP Message Security) 1.0 (accepts 1.1):
	@code
	#import "wsse.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsseapi.h"
	soap_register_plugin(soap, soap_wsse); // register the wsse plugin in your code
	// See the user guide gsoap/doc/wsse/html/index.html
	@endcode
    - WS-Security (SOAP Message Security) 1.1 (accepts 1.0):
	@code
	#import "wsse11.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsseapi.h"
	soap_register_plugin(soap, soap_wsse); // register the wsse plugin in your code
	// See the user guide gsoap/doc/wsse/html/index.html
	@endcode
    - HTTP Digest Authentication:
	@code
	#include "plugin/httpda.h"
	soap_register_plugin(soap, soap_http_da); // register the HTTP DA plugin in your code
	// See the user guide gsoap/doc/httpda/html/index.html
	@endcode
*/


/******************************************************************************\
 *                                                                            *
 * XML Data Binding                                                           *
 *                                                                            *
\******************************************************************************/


/**

@page page_XMLDataBinding XML Data Binding

SOAP/XML services use data bindings contractually bound by WSDL and auto-
generated by wsdl2h and soapcpp2 (see Service Bindings). Plain data bindings
are adopted from XML schemas as part of the WSDL types section or when running
wsdl2h on a set of schemas to produce non-SOAP-based XML data bindings.

The following readers and writers are C/C++ data type (de)serializers auto-
generated by wsdl2h and soapcpp2. Run soapcpp2 on this file to generate the
(de)serialization code, which is stored in soapC.c[pp]. Include "soapH.h" in
your code to import these data type and function declarations. Only use the
soapcpp2-generated files in your project build. Do not include the wsdl2h-
generated .h file in your code.

Data can be read in XML and deserialized from:
  - a file descriptor, using soap->recvfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->is = ...
  - a buffer, using the soap->frecv() callback

Data can be serialized in XML and written to:
  - a file descriptor, using soap->sendfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->os = ...
  - a buffer, using the soap->fsend() callback

The following options are available for (de)serialization control:
  - soap->encodingStyle = NULL; to remove SOAP 1.1/1.2 encodingStyle
  - soap_mode(soap, SOAP_XML_TREE); XML without id-ref (no cycles!)
  - soap_mode(soap, SOAP_XML_GRAPH); XML with id-ref (including cycles)
  - soap_set_namespaces(soap, struct Namespace *nsmap); to set xmlns bindings


@section ns2 Top-level root elements of schema "http://tempuri.org/Imports"

@section ns1 Top-level root elements of schema "http://tempuri.org/"

  - <ns1:GetListINC> @ref _ns1__GetListINC
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__GetListINC(struct soap*, struct _ns1__GetListINC*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__GetListINC(struct soap*, struct _ns1__GetListINC*);
    @endcode

  - <ns1:GetListINCResponse> @ref _ns1__GetListINCResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__GetListINCResponse(struct soap*, struct _ns1__GetListINCResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__GetListINCResponse(struct soap*, struct _ns1__GetListINCResponse*);
    @endcode

  - <ns1:UpdateStatusINC> @ref _ns1__UpdateStatusINC
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__UpdateStatusINC(struct soap*, struct _ns1__UpdateStatusINC*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__UpdateStatusINC(struct soap*, struct _ns1__UpdateStatusINC*);
    @endcode

  - <ns1:UpdateStatusINCResponse> @ref _ns1__UpdateStatusINCResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__UpdateStatusINCResponse(struct soap*, struct _ns1__UpdateStatusINCResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__UpdateStatusINCResponse(struct soap*, struct _ns1__UpdateStatusINCResponse*);
    @endcode

@section ns3 Top-level root elements of schema "http://schemas.microsoft.com/2003/10/Serialization/"

  - <ns3:anyType> (use wsdl2h option -g to auto-generate)

  - <ns3:anyURI> (use wsdl2h option -g to auto-generate)

  - <ns3:base64Binary> (use wsdl2h option -g to auto-generate)

  - <ns3:boolean> (use wsdl2h option -g to auto-generate)

  - <ns3:byte> (use wsdl2h option -g to auto-generate)

  - <ns3:dateTime> (use wsdl2h option -g to auto-generate)

  - <ns3:decimal> (use wsdl2h option -g to auto-generate)

  - <ns3:double> (use wsdl2h option -g to auto-generate)

  - <ns3:float> (use wsdl2h option -g to auto-generate)

  - <ns3:int> (use wsdl2h option -g to auto-generate)

  - <ns3:long> (use wsdl2h option -g to auto-generate)

  - <ns3:QName> (use wsdl2h option -g to auto-generate)

  - <ns3:short> (use wsdl2h option -g to auto-generate)

  - <ns3:string> (use wsdl2h option -g to auto-generate)

  - <ns3:unsignedByte> (use wsdl2h option -g to auto-generate)

  - <ns3:unsignedInt> (use wsdl2h option -g to auto-generate)

  - <ns3:unsignedLong> (use wsdl2h option -g to auto-generate)

  - <ns3:unsignedShort> (use wsdl2h option -g to auto-generate)

  - <ns3:char> (use wsdl2h option -g to auto-generate)

  - <ns3:duration> (use wsdl2h option -g to auto-generate)

  - <ns3:guid> (use wsdl2h option -g to auto-generate)

*/

/* End of rcx.h */
